server:
  port: 8889

#mybatis打印日志，注意是mapper的包
logging:
  level:
     com.hubpd.bigscreen.mapper: debug

# UAR_BASIC 数据源配置--用于获取指定机构下面的所有用户
uar_basic:
  datasource:
    url: jdbc:mysql://10.10.32.62:3306/UAR_BASIC?useUnicode=true&characterEncoding=utf8
    username: uardev
    password: uardev2017
    driverClassName: com.mysql.jdbc.Driver

# weishu 数据源配置--用于获取微信相关数据
weishu_pdmi:
  datasource:
    url: jdbc:mysql://10.10.32.62:3306/pdmi?useUnicode=true&characterEncoding=utf8
    username: uardev
    password: uardev2017
    driverClassName: com.mysql.jdbc.Driver

# 大屏接口数据返回值记录缓存库---包含uar_tag_dic_region和uar_origin_return_record表
origin_return:
  datasource:
    url: jdbc:mysql://10.10.32.62:3306/UAR_PROFILE?useUnicode=true&characterEncoding=utf8
    username: uardev
    password: uardev2017
    driverClassName: com.mysql.jdbc.Driver

# UAR_STATISTIC 数据源配置--用于获取指定应用下的pv、uv
uar_statistic:
  datasource:
    url: jdbc:mysql://10.10.32.62:3306/UAR_STATISTIC?useUnicode=true&characterEncoding=utf8
    username: uardev
    password: uardev2017
    driverClassName: com.mysql.jdbc.Driver


# es画像生产环境库--用于兼容老的画像接口
spring:
   data:
      elasticsearch: #ElasticsearchProperties
          cluster-name: elasticsearch_uar
          cluster-nodes: 10.101.67.5:9300
# Redis服务器连接密码（默认为空）---生产环境
  redis:
      password:
      cluster:
          nodes: 10.101.67.4:7000,10.101.67.5:7000,10.101.67.6:7000
      pool:
          max-active: 8
          max-wait: 3000
          max-idle: 8
          min-idle: 0
      timeout: 0
      commandTimeout: 3000