server:
  port: 8889

## master 数据源配置
master:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: root_123
    driverClassName: com.mysql.jdbc.Driver

## cluster 数据源配置
cluster:
  datasource:
#    url: jdbc:mysql://10.101.67.9:3306/pdmi?useUnicode=true&characterEncoding=utf8
#    username: lvsijia
#    password: lvsijia
#    driverClassName: com.mysql.jdbc.Driver
spring:
     data:
        elasticsearch: #ElasticsearchProperties
            cluster-name: elasticsearch_uar
            cluster-nodes: 10.101.67.4:9300,10.101.67.6:9300